add_newline = true

[python]
format=' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format='v${major}.${minor}'
symbol='ğŸ'


[docker_context]
disabled=true

[package]
disabled=true
